name: Continuous Integration

on:
  push:
    branches:
      - "main"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.7
      # - name: Install dependencies
      #   run: go get .
      # - name: Build
      #   run: go build -v ./...
      # - name: list dir
      #   run: ls -ltrh
      - name: build
        run: go build -o main
      - name: change permissions
        run: chmod +x main
      - name: start server
        run: ./main &
      - name: test
        run: go test -v ./tests

        
